---
name: Build spc

on:
  push:
    branches:
      - lahari
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  Build_Java_Application:
    name: Cloning the repo and setting up the environment to build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out to repo
        uses: actions/checkout@v3 # We use "uses" in the steps when we are using predefined github-action
      
      - name: Install java-17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y

      - name: Build java
        run: ./mvnw package && ls -al **/target
